apiVersion: v1
kind: Service
metadata:
  name: stt-server
spec:
  selector:
    app: stt-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 32051
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 32080
  type: NodePort
